# Generated by Django 6.0 on 2025-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movierating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movierating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
