# Generated by Django 6.0 on 2025-12-16 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movierating_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_items', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Hero Movie',
                'verbose_name_plural': 'Hero Movies',
                'ordering': ['priority', '-updated_at'],
            },
        ),
    ]
