# Generated by Django 6.0 on 2025-12-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_heromovie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heromovie',
            options={'ordering': ['priority', '-updated_at']},
        ),
        migrations.AddField(
            model_name='heromovie',
            name='keyword',
            field=models.CharField(blank=True, help_text='예: 개봉임박, 오스카 수상, 평론가 극찬', max_length=50),
        ),
    ]
