# Generated by Django 4.2.8 on 2023-12-18 10:00
from django.db import migrations
from django.db.models import Count

def remove_duplicates(apps, schema_editor):
    MovieRating = apps.get_model('movies', 'MovieRating')

    # Find user/movie pairs with more than one rating
    duplicates = (
        MovieRating.objects.values('user', 'movie')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        user_id = duplicate['user']
        movie_id = duplicate['movie']

        # Get all ratings for this user/movie pair, ordered by most recent first
        ratings = MovieRating.objects.filter(
            user_id=user_id,
            movie_id=movie_id
        ).order_by('-updated_at')

        # Keep the first one (the most recent) and delete the rest
        ratings_to_delete = ratings[1:]
        for rating in ratings_to_delete:
            rating.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_genre_id'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]