# Generated by Django 4.2.16 on 2025-12-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_actor_director_movie_actors_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_person_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('character', models.CharField(blank=True, max_length=100)),
                ('profile_path', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=99)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='movies.movie')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
