# Generated by Django 4.2.16 on 2025-12-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='profile_path',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='tmdb_person_id',
        ),
        migrations.AddField(
            model_name='cast',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cast_roles', to='movies.actor'),
        ),
    ]
