# Generated by Django 4.2.16 on 2025-12-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_alter_chatmessage_id_alter_chatsession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
