# Generated by Django 4.2.16 on 2025-12-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_chatsession_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_recommended_movie_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
